//! Deterministic `fastly.toml` / `wrangler.toml` generation from an
//! [`EdgeConfig`] (SPEC §9: reproducible, diffable output).
//!
//! Conventions:
//!
//! * Origins are emitted sorted by alias (the config model stores them in a
//!   `HashMap`, so iteration order must not leak into output).
//! * `fastly.toml` carries the deploy-time `[setup]` section (D15: codegen
//!   targets `[setup]`); an existing `[local_server]` section — Viceroy
//!   testing config, not derivable from `edge.toml` — is preserved verbatim.
//! * `wrangler.toml` KV namespaces omit `id`: wrangler auto-provisions
//!   resources and writes the ids back on deploy (verified against wrangler
//!   4.125.0 config schema). Fetch permissions need no config: no
//!   allowlist key exists in wrangler (SPEC §14 open question 1, resolved
//!   2026-08-24) — outbound fetch is allow-by-default on Workers.

use edge_core::config::EdgeConfig;

/// Compatibility date baked into generated `wrangler.toml`; matches the
/// workerd configs the conformance suite runs under.
pub const DEFAULT_COMPATIBILITY_DATE: &str = "2025-08-01";

/// The default `main` entry for generated `wrangler.toml` (worker-build
/// output).
pub const DEFAULT_WRANGLER_MAIN: &str = "build/index.js";

const GENERATED_HEADER: &str = "# Generated by edge-cli from edge.toml — do not edit by hand.\n\
                                # Regenerate with: edge-cli generate\n";

/// Render the deploy-time `fastly.toml` for `config`.
///
/// `existing_fastly` is the current file (if any); its `[local_server]`
/// section is preserved so Viceroy testing configs survive regeneration.
pub fn fastly_toml(config: &EdgeConfig, existing_fastly: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');

    let name = &config.service().name;
    out.push_str(&format!("name = {name:?}\n"));
    out.push_str(&format!("description = {name:?}\n"));
    out.push_str("authors = [\"edge\"]\n");
    out.push_str("language = \"rust\"\n");
    out.push('\n');

    out.push_str("[setup]\n");

    // Origins, sorted by alias for deterministic output. `[setup.backends]`
    // is keyed by BACKEND name (what the resolver looks up via
    // `Backend::from_name`), not the alias.
    let mut origins: Vec<_> = config.origins().collect();
    origins.sort_by_key(|(a, _)| *a);
    if !origins.is_empty() {
        let backends: Vec<String> = origins
            .iter()
            .map(|(_, origin)| {
                let host = origin.url.host_str().unwrap_or_default();
                let use_ssl = origin.url.scheme() == "https";
                format!(
                    "{} = {{ target = {host:?}, override_host = {host:?}, use_ssl = {use_ssl} }}",
                    origin.backend
                )
            })
            .collect();
        out.push_str(&format!("backends = {{ {} }}\n", backends.join(", ")));
    }

    let stores = config.stores();
    if let Some(kv) = &stores.kv {
        out.push_str(&format!("kv_store = {{ name = {kv:?} }}\n"));
    }
    if let Some(cfg) = &stores.config {
        out.push_str(&format!("config_store = {{ name = {cfg:?} }}\n"));
    }
    if let Some(secrets) = &stores.secrets {
        out.push_str(&format!("secret_store = {{ name = {secrets:?} }}\n"));
    }
    out.push('\n');

    if let Some(endpoint) = &config.logging().endpoint {
        out.push_str("[logging]\n");
        out.push_str(&format!("{endpoint} = {{ name = {endpoint:?} }}\n"));
        out.push('\n');
    }

    if let Some(local_server) = extract_local_server(existing_fastly) {
        out.push_str(local_server.as_str());
    }

    out
}

/// Render `wrangler.toml` for `config`.
pub fn wrangler_toml(config: &EdgeConfig, compatibility_date: &str) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');

    out.push_str(&format!("name = {:?}\n", config.service().name));
    out.push_str(&format!("main = {DEFAULT_WRANGLER_MAIN:?}\n"));
    out.push_str(&format!("compatibility_date = {compatibility_date:?}\n"));
    out.push('\n');

    if let Some(kv) = &config.stores().kv {
        out.push_str("# KV namespace binding (auto-provisioned: wrangler writes\n");
        out.push_str("# the namespace id back here on the first deploy).\n");
        out.push_str("[[kv_namespaces]]\n");
        out.push_str(&format!("binding = {kv:?}\n"));
        out.push('\n');
    }

    out.push_str("# Vars/secrets live in platform configs (edge.toml [stores] binds\n");
    out.push_str("# them); add values here or via `wrangler secret put`.\n");
    out.push_str("[vars]\n");

    out
}

/// Extract and re-render the `[local_server]` table from an existing
/// `fastly.toml`, if present (Viceroy testing config — preserved so the
/// harness keeps working after regeneration).
fn extract_local_server(existing: Option<&str>) -> Option<String> {
    let existing = existing?;
    let doc: toml::Value = toml::from_str(existing).ok()?;
    let local_server = doc.get("local_server")?;
    if local_server.as_table()?.is_empty() {
        return None;
    }
    let wrapper = toml::Value::Table(
        [("local_server".to_string(), local_server.clone())]
            .into_iter()
            .collect(),
    );
    let mut rendered = toml::to_string_pretty(&wrapper).ok()?;
    if !rendered.ends_with('\n') {
        rendered.push('\n');
    }
    Some(rendered)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config(toml_str: &str) -> EdgeConfig {
        EdgeConfig::from_toml_str(toml_str).unwrap()
    }

    const VALID: &str = r#"
[service]
name = "svc"

[origins]
api = { url = "https://api.example.com", backend = "api_backend" }
cdn = { url = "http://cdn.example.net:8080", backend = "cdn_backend" }

[stores]
kv = "edge_kv"
config = "edge_config"
secrets = "edge_secrets"

[logging]
endpoint = "default_logging"

[fastly]
dynamic_backends = false
"#;

    #[test]
    fn fastly_toml_is_deterministic_and_sorted() {
        let cfg = config(VALID);
        let a = fastly_toml(&cfg, None);
        let b = fastly_toml(&cfg, None);
        assert_eq!(a, b, "generation must be reproducible");

        // Origins sorted by alias: api < cdn, so api first.
        let api_pos = a.find("api_backend").unwrap();
        let cdn_pos = a.find("cdn_backend").unwrap();
        assert!(api_pos < cdn_pos, "origins must be sorted by alias");

        assert!(a.contains("target = \"api.example.com\""));
        assert!(a.contains("override_host = \"api.example.com\""));
        assert!(a.contains("use_ssl = true"));
        assert!(a.contains("use_ssl = false"));
        assert!(a.contains("kv_store = { name = \"edge_kv\" }"));
        assert!(a.contains("config_store = { name = \"edge_config\" }"));
        assert!(a.contains("secret_store = { name = \"edge_secrets\" }"));
        assert!(a.contains("[logging]"));
        assert!(a.contains("default_logging = { name = \"default_logging\" }"));
    }

    #[test]
    fn local_server_is_preserved() {
        let cfg = config(VALID);
        let existing = r#"
name = "svc"
[local_server.backends]
api_backend = { url = "http://127.0.0.1:18080", override_host = "api.example.com" }
"#;
        let generated = fastly_toml(&cfg, Some(existing));
        assert!(
            generated.contains("127.0.0.1:18080"),
            "local_server must survive regeneration:\n{generated}"
        );
        assert!(
            generated.contains("override_host = \"api.example.com\""),
            "local_server content must survive:\n{generated}"
        );

        // No existing file -> no local_server section.
        assert!(!fastly_toml(&cfg, None).contains("local_server"));
    }

    #[test]
    fn wrangler_toml_basics() {
        let cfg = config(VALID);
        let out = wrangler_toml(&cfg, DEFAULT_COMPATIBILITY_DATE);
        assert!(out.contains("name = \"svc\""));
        assert!(out.contains("main = \"build/index.js\""));
        assert!(out.contains("compatibility_date = \"2025-08-01\""));
        assert!(out.contains("binding = \"edge_kv\""));
        // No fetch-permission config: no such wrangler key (resolved 2026-08-24).
        assert!(!out.contains("permission"));
    }

    #[test]
    fn empty_origins_omit_backends() {
        let cfg = config(
            "[service]\nname = \"x\"\n[origins]\n[stores]\n[logging]\n[fastly]\ndynamic_backends = false\n",
        );
        let out = fastly_toml(&cfg, None);
        assert!(!out.contains("backends ="));
        assert!(out.contains("name = \"x\""));
    }
}
