//! # edge-cloudflare
//!
//! Cloudflare Workers adapter for the Edge SDK (SPEC §8.1).
//!
//! Bridges the platform-agnostic core (`edge_core`) to the workers-rs SDK
//! (`worker` 0.8.5, pinned, `http` feature). Built only for
//! `wasm32-unknown-unknown` (SPEC §5); the `worker` crate cannot run on the
//! host.
//!
//! The service entry is generated by `#[edge_core::main]` under
//! `--features cloudflare` (SPEC §6.2):
//!
//! ```ignore
//! #[edge_cloudflare::wasm_bindgen::prelude::wasm_bindgen]
//! pub fn fetch(req: web_sys::Request, env: Env, ctx: JsContext) -> js_sys::Promise {
//!     future_to_promise(AssertUnwindSafe(async move {
//!         // -> edge_cloudflare::serve_fetch(req, env, config, __handler).await
//!     }))
//! }
//! ```
//!
//! # Execution model
//!
//! Workers run on the JS event loop; the handler future is driven natively by
//! the runtime (no executor needed, SPEC §8.1). Unlike the Fastly adapter
//! (SPEC §8.3), `Context` methods here are genuinely async — `fetch` awaits a
//! Promise — so concurrent awaits (`join!`/`select!`) work on Cloudflare.
//!
//! # Send/Sync
//!
//! Everything crossing into `edge-core` is plain data (`Bytes`, `String`);
//! JS objects are held only inside the adapter and never cross the boundary
//! (SPEC §8.1).

#![deny(unsafe_code)]
#![warn(missing_docs)]
#![warn(missing_debug_implementations)]

mod convert;
mod kv;
mod platform;
mod send;

pub use worker::{js_sys, wasm_bindgen, worker_sys};

/// Workers-rs types re-exported for the macro-generated entry signature
/// (SPEC §6.2): `fetch(web_sys::Request, Env, Context) -> js_sys::Promise`.
pub use worker::{console_error, console_log, Context as WorkerContext, Env as WorkerEnv};

use std::future::Future;

use edge_core::{config::EdgeConfig, Context, EdgeRequest, EdgeResponse, Error, Result};

/// Run `handler` for an incoming request (called by the macro-generated
/// `fetch`).
///
/// 1. Convert and buffer the `web_sys::Request`.
/// 2. Build the [`Context`] from `env` + the embedded `config` (bindings per
///    SPEC §8.1; the `default` KV handle resolves to `[stores] kv`).
/// 3. Await the handler (native async — no executor needed).
/// 4. Convert the response to `web_sys::Response`.
pub async fn serve_fetch<F, Fut>(
    req: web_sys::Request,
    env: WorkerEnv,
    config: EdgeConfig,
    handler: F,
) -> Result<web_sys::Response>
where
    F: FnOnce(EdgeRequest, Context) -> Fut,
    Fut: Future<Output = Result<EdgeResponse>>,
{
    let metadata = platform::capture_client_metadata(&req);
    let edge_req = convert::request_to_edge(req).await?;
    let ctx = platform::CloudflarePlatform::context(env, config, metadata);
    let handler_ctx = ctx.clone();
    match handler(edge_req, handler_ctx).await {
        Ok(resp) => convert::response_from_edge(resp, &ctx).await,
        Err(e) => {
            // Catch-all responses also carry the finalized log fields (P9);
            // the control header is stripped/set on the synthetic response.
            let mut ws_resp = error_to_response(&e);
            ws_resp = convert::apply_control_header(ws_resp, &ctx);
            Ok(ws_resp)
        }
    }
}

/// Convert a handler error into a client response (SPEC §6.2).
///
/// Router misses become `404 Not Found`; everything else is a `500 Internal
/// Server Error` with the error string — the same convention as
/// `fastly::main` and `edge_fastly::serve` (parity, decision D12).
pub fn error_to_response(e: &Error) -> web_sys::Response {
    let status = match e {
        Error::Router(edge_core::PathError::NotFound) => 404,
        _ => 500,
    };
    worker::Response::error(e.to_string(), status)
        .expect("Response::error with a valid status cannot fail")
        .into()
}
