//! hello-world — the canonical Edge SDK example (SPEC §10). One handler
//! source, two platform entries:
//!
//! * **Cloudflare** — this lib is the `cdylib` worker-build consumes; the
//!   `fetch` export is generated by `#[edge_core::main]` under
//!   `--features cloudflare` (`mod entry`).
//! * **Fastly** — `src/main.rs` is a thin bin whose `#[edge_core::main]`
//!   entry (under `--features fastly`) calls [`handle`].
//!
//! Build:
//!
//! ```text
//! # Cloudflare (then: worker-build && wrangler deploy)
//! cargo build --target wasm32-unknown-unknown --features cloudflare -p hello-world
//! # Fastly (then: fastly compute deploy)
//! cargo build --target wasm32-wasip1 -p hello-world --features fastly
//! ```

use edge_core::router::{handler, RouteParams};
use edge_core::{Context, EdgeRequest, EdgeResponse, ResponseExt, Result, Router};

async fn hello(req: EdgeRequest, _params: RouteParams, ctx: Context) -> Result<EdgeResponse> {
    let greeting = ctx.var("GREETING").unwrap_or_else(|| "Hello".to_string());
    edge_core::log::info!(ctx, "greeting request at {}", req.uri().path());
    let mut resp = EdgeResponse::ok(format!("{greeting}, world! (path {})", req.uri().path()));
    resp.headers_mut()
        .insert("x-edge", "hello-world".parse().unwrap());
    Ok(resp)
}

async fn greet(req: EdgeRequest, params: RouteParams, ctx: Context) -> Result<EdgeResponse> {
    let name = params.get("name").unwrap_or("world");
    edge_core::log::info!(ctx, "greeting {} from {}", name, req.uri().path());
    Ok(EdgeResponse::ok(format!("hello {name}!")))
}

/// Dispatch a request through the shared router (called by both platform
/// entries).
pub async fn handle(req: EdgeRequest, mut ctx: Context) -> Result<EdgeResponse> {
    let mut router = Router::new();
    router.get("/", handler(hello))?;
    router.get("/hello/:name", handler(greet))?;
    router.handle(req, &mut ctx).await
}

/// Cloudflare entry: exported as `fetch` from the cdylib.
#[cfg(feature = "cloudflare")]
mod entry {
    use super::*;

    #[edge_core::main]
    pub async fn edge_main(req: EdgeRequest, ctx: Context) -> Result<EdgeResponse> {
        crate::handle(req, ctx).await
    }
}
