//! # edge-fastly
//!
//! Fastly Compute adapter for the Edge SDK (SPEC §8.2, §8.3).
//!
//! Bridges the platform-agnostic core (`edge_core`) to the Fastly SDK
//! (`fastly` 0.13, pinned). Built only for the `wasm32-wasip1`/`wasm32-wasip2`
//! targets (SPEC §5); host calls fail at runtime on other targets.
//!
//! The service entry is generated by `#[edge_core::main]` under
//! `--features fastly`:
//!
//! ```ignore
//! fn main() -> Result<(), edge_fastly::Error> {
//!     edge_fastly::serve(
//!         __edge_main_impl,
//!         edge_core::config::EdgeConfig::from_toml_str(include_str!("../edge.toml"))?,
//!     )
//! }
//! ```
//!
//! # Execution model (SPEC §8.3)
//!
//! `#[fastly::main]` is synchronous and the SDK ships no executor. This
//! adapter drives the async handler with a minimal poll-loop executor whose
//! futures never return `Pending` in practice: every `Context` method is
//! implemented over blocking host calls (`send`, sync KV). Concurrent awaits
//! over adapter futures are unsupported on Fastly in v1; sequential awaits
//! work.

#![warn(missing_docs)]
#![warn(missing_debug_implementations)]

mod convert;
mod drive;
mod kv;
mod platform;
mod resolve;

pub use fastly::Error;

use edge_core::{config::EdgeConfig, Context, EdgeRequest, EdgeResponse, Result};

/// Build the Fastly-backed [`Context`] for the current request.
///
/// Store/logging bindings are resolved from `config` (SPEC §8.2); missing
/// stores degrade to `None` lookups rather than failing the request.
pub fn context(config: EdgeConfig) -> Context {
    context_with_metadata(
        config,
        edge_core::client::ClientMetadata::empty(edge_core::client::EdgeProvider::Fastly),
    )
}

/// Build the Fastly-backed [`Context`] for the current request, with the
/// request's client metadata snapshot (M10).
pub fn context_with_metadata(
    config: EdgeConfig,
    metadata: edge_core::client::ClientMetadata,
) -> Context {
    platform::FastlyPlatform::context(config, metadata)
}

/// Run `handler` as the Fastly service entry (SPEC §8.2, §8.3).
///
/// 1. `fastly::init()` (ABI version handshake, as `fastly::main` does).
/// 2. Read the client request and buffer its body.
/// 3. Build the [`Context`] from `config`.
/// 4. Drive the async handler with the poll-loop executor.
/// 5. Send the response; handler errors become a 500 (or 404 for router
///    misses) with the error string — same convention as `fastly::main`
///    (SPEC §6.2).
///
/// Returns `Ok(())` in practice: all recoverable failures are turned into
/// client responses. `Err` is reserved for host-level failures in producing
/// that response.
pub fn serve<F, Fut>(handler: F, config: EdgeConfig) -> std::result::Result<(), fastly::Error>
where
    F: FnOnce(EdgeRequest, Context) -> Fut,
    Fut: std::future::Future<Output = Result<EdgeResponse>>,
{
    fastly::init();
    let (req, metadata) = convert::request_from_client();
    let ctx = platform::FastlyPlatform::context(config, metadata);
    let handler_ctx = ctx.clone();
    let outcome = drive::drive(async move { handler(req, handler_ctx).await });
    // SPEC-PORTABILITY-PRIMITIVES §6: structured log fields are finalized
    // for every request outcome — successful, synthetic, timeout, and
    // catch-all — before the response goes out. The Fastly finalize emits
    // the structured record to the configured log endpoint (or the stderr
    // fallback); fields never ride in the client response.
    ctx.finalize_log_fields();
    match outcome {
        Ok(resp) => convert::response_to_client(resp, &ctx),
        Err(e) => convert::error_to_client(&e),
    }
    Ok(())
}
